export enum EscrowStatus {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_LOCKED = "PAYMENT_LOCKED",
  SHIPMENT_CONFIRMED = "SHIPMENT_CONFIRMED",
  COMPLETED = "COMPLETED",
  DISPUTED = "DISPUTED",
  REFUNDED = "REFUNDED",
}
